# Generated by Django 5.2.6 on 2025-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=20)),
                ('dom', models.DateField()),
                ('color', models.CharField(max_length=20)),
                ('engine_type', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=20)),
            ],
        ),
    ]
